version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biometria_frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Puerto manejado por Traefik/Dokploy